const actionConstants = {
    FETCH_MOVIE_LIST_ASYNC : "FETCH_MOVIE_LIST_ASYNC",
    FETCH_MOVIE_LIST_ASYNC_REQUEST : "FETCH_MOVIE_LIST_ASYNC_REQUEST",
    FETCH_MOVIE_LIST_ASYNC_RESPONSE : "FETCH_MOVIE_LIST_ASYNC_RESPONSE",
    SELECT_MOVIE : "SELECT_MOVIE",
    FILTER_MOVIE_BY_GENRE : "FILTER_MOVIE_BY_GENRE",
    SORT_MOVIE_LIST : "SORT_MOVIE_LIST",
}

export default actionConstants;