const actionConstants = {
    FETCH_MOVIE_LIST_ASYNC : "FETCH_MOVIE_LIST_ASYNC",
    FETCH_MOVIE_LIST_ASYNC_REQUEST : "FETCH_MOVIE_LIST_ASYNC_REQUEST",
    FETCH_MOVIE_LIST_ASYNC_RESPONSE : "FETCH_MOVIE_LIST_ASYNC_RESPONSE",
    SELECT_MOVIE : "SELECT_MOVIE",
}

export default actionConstants;